services:
  - type: web
    name: global-app
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RENDER_PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_ENV
        value: production
    plan: free
